# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
