# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20170126_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
